const SUPABASE_URL='https://uysehlmmxgmfrpkhjcfn.supabase.co';const SUPABASE_KEY='sb_publishable_CBJSE4rECgDP1C69xF54Qg_WGxdnkjk';const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);const msg=t=>$('#loginMsg').textContent=t;
async function requireAdmin(){const {data:{session}}=await db.auth.getSession();if(!session){$('#loginBox').classList.remove('hidden');return false}const {data:user}=await db.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!user){await db.auth.signOut();$('#loginBox').classList.remove('hidden');msg('این حساب دسترسی مدیر ندارد. ابتدا شناسه آن را در جدول admin_users ثبت کنید.');return false}$('#loginBox').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');await loadAll();return true}
$('#login').onclick=async()=>{msg('در حال ورود...');const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){msg('ورود ناموفق: '+error.message);return}await requireAdmin()};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('#tab-'+b.dataset.tab).classList.remove('hidden')});
async function loadAll(){await Promise.all([loadPosters(),loadEvents(),loadAudios(),loadSettings()])}
function publicUrl(bucket,path){return path?db.storage.from(bucket).getPublicUrl(path).data.publicUrl:''}
async function loadPosters(){const {data,error}=await db.from('posters').select('*').order('sort_order').order('created_at',{ascending:false});if(error)return;$('#posterItems').innerHTML=(data||[]).map(p=>'<div class="item"><img src="'+publicUrl('posters',p.image_path)+'"><h3>'+p.title+'</h3><div class="row"><button class="btn danger" onclick="deletePoster(\''+p.id+'\',\''+p.image_path.replaceAll("'","\\'")+'\')">حذف</button></div></div>').join('')||'<p>هنوز پوستری ثبت نشده.</p>'}
window.deletePoster=async(id,path)=>{if(!confirm('این پوستر حذف شود؟'))return;await db.from('posters').delete().eq('id',id);if(path)await db.storage.from('posters').remove([path]);await loadPosters()};
$('#addPoster').onclick=async()=>{const f=$('#posterFile').files[0],title=$('#posterTitle').value.trim()||'پوستر مراسم';if(!f)return alert('یک تصویر انتخاب کنید.');const path=crypto.randomUUID()+'-'+f.name.replace(/[^\w\-.]+/g,'-');const up=await db.storage.from('posters').upload(path,f,{upsert:false});if(up.error)return alert(up.error.message);const ins=await db.from('posters').insert({title,image_path:path,sort_order:Date.now()});if(ins.error){await db.storage.from('posters').remove([path]);return alert(ins.error.message)}$('#posterTitle').value='';$('#posterFile').value='';await loadPosters()};
async function loadEvents(){const {data}=await db.from('events').select('*').order('event_date',{ascending:false});$('#eventItems').innerHTML=(data||[]).map(e=>'<div class="item"><h3>'+e.title+'</h3><p>'+(e.event_date?new Date(e.event_date).toLocaleString('fa-IR'):'')+'</p><p>'+(e.location||'')+'</p><button class="btn danger" onclick="deleteEvent(\''+e.id+'\')">حذف</button></div>').join('')||'<p>هنوز مراسمی ثبت نشده.</p>'}
window.deleteEvent=async id=>{if(confirm('این مراسم حذف شود؟')){await db.from('events').delete().eq('id',id);await loadEvents()}};
$('#addEvent').onclick=async()=>{const title=$('#eventTitle').value.trim();if(!title)return alert('عنوان مراسم را وارد کنید.');const {error}=await db.from('events').insert({title,event_date:$('#eventDate').value?new Date($('#eventDate').value).toISOString():null,location:$('#eventLocation').value.trim(),description:$('#eventDescription').value.trim()});if(error)return alert(error.message);['eventTitle','eventDate','eventLocation','eventDescription'].forEach(id=>$('#'+id).value='');await loadEvents()};
async function loadAudios(){const {data}=await db.from('audios').select('*').order('created_at',{ascending:false});$('#audioItems').innerHTML=(data||[]).map(a=>'<div class="item"><h3>'+a.title+'</h3><audio controls src="'+publicUrl('audios',a.audio_path)+'"></audio><p>'+((a.description)||'')+'</p><button class="btn danger" onclick="deleteAudio(\''+a.id+'\',\''+a.audio_path.replaceAll("'","\\'")+'\')">حذف</button></div>').join('')||'<p>هنوز صوتی ثبت نشده.</p>'}
window.deleteAudio=async(id,path)=>{if(!confirm('این صوت حذف شود؟'))return;await db.from('audios').delete().eq('id',id);if(path)await db.storage.from('audios').remove([path]);await loadAudios()};
$('#addAudio').onclick=async()=>{const f=$('#audioFile').files[0],title=$('#audioTitle').value.trim()||'صوت جدید';if(!f)return alert('یک فایل صوتی انتخاب کنید.');const path=crypto.randomUUID()+'-'+f.name.replace(/[^\w\-.]+/g,'-');const up=await db.storage.from('audios').upload(path,f,{upsert:false});if(up.error)return alert(up.error.message);const ins=await db.from('audios').insert({title,description:$('#audioDescription').value.trim(),audio_path:path});if(ins.error){await db.storage.from('audios').remove([path]);return alert(ins.error.message)}$('#audioTitle').value='';$('#audioDescription').value='';$('#audioFile').value='';await loadAudios()};
async function loadSettings(){const {data}=await db.from('site_settings').select('*').eq('id',true).maybeSingle();if(!data)return;$('#siteTitleInput').value=data.site_title||'';$('#siteSubtitleInput').value=data.site_subtitle||'';$('#aboutInput').value=data.about_text||'';$('#telegramInput').value=data.telegram_url||'';$('#instagramInput').value=data.instagram_url||'';$('#eitaaInput').value=data.eitaa_url||'';$('#baleInput').value=data.bale_url||''}
$('#saveSettings').onclick=async()=>{const {error}=await db.from('site_settings').upsert({id:true,site_title:$('#siteTitleInput').value.trim(),site_subtitle:$('#siteSubtitleInput').value.trim(),about_text:$('#aboutInput').value.trim(),telegram_url:$('#telegramInput').value.trim(),instagram_url:$('#instagramInput').value.trim(),eitaa_url:$('#eitaaInput').value.trim(),bale_url:$('#baleInput').value.trim(),updated_at:new Date().toISOString()});alert(error?error.message:'اطلاعات سایت ذخیره شد.')};
requireAdmin();